package com.example.ui

object LocalStrings {
    private val translations = mapOf(
        "en" to mapOf(
            "dashboard" to "Dashboard",
            "home" to "Home",
            "track" to "Track",
            "lifestyle" to "Lifestyle",
            "more" to "More",
            "settings" to "Settings",
            
            // Medical parameters
            "blood_pressure" to "Blood Pressure",
            "blood_sugar" to "Blood Sugar",
            "weight" to "Weight",
            "heart_rate" to "Heart Rate",
            "sleep" to "Sleep",
            "cholesterol" to "Cholesterol",
            "triglycerides" to "Triglycerides",
            "medications" to "Medications",
            "symptoms" to "Symptoms",
            "lab_results" to "Lab Results",
            "smoking" to "Smoking",
            "water_intake" to "Water Intake",
            "exercise" to "Exercise",
            "attachments" to "Attachments",
            "emergency_info" to "Emergency Info",
            "health_summary" to "Health Summary",
            "search" to "Search",
            "ai_health_assistant" to "AI Health Assistant",
            
            // Subtitles/Status
            "elevated" to "ELEVATED",
            "normal" to "NORMAL",
            "high" to "HIGH",
            "low" to "LOW",
            "dosage" to "Dosage",
            "frequency" to "Frequency",
            "notes" to "Notes",
            "timestamp" to "Date/Time",
            "active" to "Active",
            "inactive" to "Inactive",
            "severity" to "Severity",
            "reference_range" to "Reference Range",
            "allergies" to "Allergies",
            "chronic_conditions" to "Chronic Conditions",
            "blood_type" to "Blood Type",
            "full_name" to "Full Name",
            "emergency_contact" to "Emergency Contact Name",
            "emergency_phone" to "Emergency Contact Phone",
            "additional_notes" to "Additional Medical Notes",

            // Actions & Settings
            "theme" to "Theme",
            "system" to "SYSTEM",
            "light" to "LIGHT",
            "dark" to "DARK",
            "language" to "Language",
            "height_bmi" to "Height (cm) for BMI",
            "save_height" to "Save height",
            "ai_provider" to "AI Provider",
            "model_name" to "Model name",
            "add_record" to "Add Record",
            "add" to "Add",
            "save" to "Save",
            "delete" to "Delete",
            "cancel" to "Cancel",
            "quick_water" to "+250ml water",
            "export_data" to "Export Data (TXT / CSV / JSON / PDF)",
            "backup_data" to "Backup (ZIP)",
            "no_records" to "No records found.",
            "api_key" to "LLM API Key (Stored securely)",
            "save_api_key" to "Save Settings & Keys",
            "enter_value" to "Enter value",
            
            // History Headers
            "history" to "History & Trends",
            "systolic" to "Systolic",
            "diastolic" to "Diastolic",
            "value" to "Value",
            "unit" to "Unit",
            "hours" to "Hours",
            "select_image" to "Attach Health Image",
            "mood" to "Mood",
            "mood_score" to "How are you feeling?",
            "family_members" to "Family Members",
            "weekly_summary" to "Weekly AI Summary",
            "water_goal" to "Daily Water Goal",
            "dose_log" to "Dose Log",
            "mark_taken" to "Mark Taken",
            "mark_skipped" to "Mark Skipped",
            "relationship" to "Relationship",
            "date_of_birth" to "Date of Birth",

            // Backup & Export for Doctor
            "export_for_doctor" to "Export for Doctor",
            "doctor_export_desc" to "Share a CSV of your Blood Pressure, Blood Sugar, Weight, Sleep, Symptom and Lab Result records with your doctor (e.g. for import into DataDoctorPro).",
            "last_sent" to "Last sent",
            "never" to "Never",
            "days_30" to "30 Days",
            "days_90" to "90 Days",
            "all_time" to "All Time",
            "send_new_records" to "Send New Records Since Last Export",
            "backup_sync" to "Backup & Restore",
            "backup_desc" to "Backup and restore your medical journal records on this device.",
            "local_backup" to "Local Device Backup",
            "last_backup" to "Last backup",
            "back_up" to "Back Up",
            "restore" to "Restore",
            "export_media_zip" to "Export Media ZIP"
        ),
        "ar" to mapOf(
            "dashboard" to "لوحة البيانات",
            "home" to "الرئيسية",
            "track" to "المتابعة",
            "lifestyle" to "نمط الحياة",
            "more" to "المزيد",
            "settings" to "الإعدادات",
            
            // Medical parameters
            "blood_pressure" to "ضغط الدم",
            "blood_sugar" to "سكر الدم",
            "weight" to "الوزن",
            "heart_rate" to "نبض القلب",
            "sleep" to "النوم",
            "cholesterol" to "الكوليسترول",
            "triglycerides" to "الدهون الثلاثية",
            "medications" to "الأدوية",
            "symptoms" to "الأعراض",
            "lab_results" to "نتائج المختبر",
            "smoking" to "التدخين",
            "water_intake" to "شرب الماء",
            "exercise" to "التمارين الرياضية",
            "attachments" to "المرفقات",
            "emergency_info" to "معلومات الطوارئ",
            "health_summary" to "ملخص صحي",
            "search" to "البحث",
            "ai_health_assistant" to "مساعد الصحة الذكي",
            
            // Subtitles/Status
            "elevated" to "مرتفع نسبيًا",
            "normal" to "طبيعي",
            "high" to "مرتفع",
            "low" to "منخفض",
            "dosage" to "الجرعة",
            "frequency" to "التكرار",
            "notes" to "ملاحظات",
            "timestamp" to "التاريخ والوقت",
            "active" to "نشط",
            "inactive" to "غير نشط",
            "severity" to "الشدة",
            "reference_range" to "النطاق المرجعي",
            "allergies" to "الحساسية",
            "chronic_conditions" to "الأمراض المزمنة",
            "blood_type" to "فصيلة الدم",
            "full_name" to "الاسم الكامل",
            "emergency_contact" to "اسم جهة اتصال الطوارئ",
            "emergency_phone" to "هاتف جهة اتصال الطوارئ",
            "additional_notes" to "ملاحظات طبية إضافية",

            // Actions & Settings
            "theme" to "المظهر",
            "system" to "النظام",
            "light" to "فاتح",
            "dark" to "داكن",
            "language" to "اللغة",
            "height_bmi" to "الطول (سم) لحساب كتلة الجسم",
            "save_height" to "حفظ الطول",
            "ai_provider" to "مزود الذكاء الاصطناعي",
            "model_name" to "اسم النموذج",
            "add_record" to "إضافة سجل",
            "add" to "إضافة",
            "save" to "حفظ",
            "delete" to "حذف",
            "cancel" to "إلغاء",
            "quick_water" to "+250مل ماء",
            "export_data" to "تصدير البيانات (TXT / CSV / JSON / PDF)",
            "backup_data" to "نسخ احتياطي (ZIP)",
            "no_records" to "لا توجد سجلات بعد.",
            "api_key" to "مفتاح API الخاص بالذكاء الاصطناعي",
            "save_api_key" to "حفظ الإعدادات والمفاتيح",
            "enter_value" to "أدخل القيمة",
            
            // History Headers
            "history" to "السجل والمؤشرات",
            "systolic" to "الانقباضي",
            "diastolic" to "الانبساطي",
            "value" to "القيمة",
            "unit" to "الوحدة",
            "hours" to "ساعات",
            "select_image" to "إرفاق صورة طبية",
            "mood" to "الحالة المزاجية",
            "mood_score" to "كيف تشعر الآن؟",
            "family_members" to "أفراد الأسرة",
            "weekly_summary" to "ملخص أسبوعي بالذكاء الاصطناعي",
            "water_goal" to "هدف الماء اليومي",
            "dose_log" to "سجل الجرعات",
            "mark_taken" to "تم أخذها",
            "mark_skipped" to "تم التخطي",
            "relationship" to "العلاقة",
            "date_of_birth" to "تاريخ الميلاد",

            // Backup & Export for Doctor
            "export_for_doctor" to "التصدير للطبيب",
            "doctor_export_desc" to "شارك ملف CSV يحتوي على سجلات ضغط الدم وسكر الدم والوزن والنوم والأعراض ونتائج المختبر مع طبيبك.",
            "last_sent" to "آخر إرسال",
            "never" to "لا يوجد",
            "days_30" to "٣٠ يوماً",
            "days_90" to "٩٠ يوماً",
            "all_time" to "كل الوقت",
            "send_new_records" to "إرسال السجلات الجديدة منذ آخر تصدير",
            "backup_sync" to "النسخ الاحتياطي والاسترداد",
            "backup_desc" to "احتفظ بنسخة احتياطية من سجلاتك الصحية أو استردّها على هذا الجهاز.",
            "local_backup" to "النسخ الاحتياطي المحلي",
            "last_backup" to "آخر نسخة احتياطية",
            "back_up" to "نسخ احتياطي",
            "restore" to "استرداد",
            "export_media_zip" to "تصدير ملفات الوسائط (ZIP)"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
