package com.example.ui

object LocalStrings {
    private val translations = mapOf(
        "en" to mapOf(
            "dashboard" to "Dashboard",
            "home" to "Home",
            "track" to "Track",
            "lifestyle" to "Lifestyle",
            "more" to "More",
            "settings" to "Settings",
            
            // Medical parameters
            "blood_pressure" to "Blood Pressure",
            "blood_sugar" to "Blood Sugar",
            "weight" to "Weight",
            "heart_rate" to "Heart Rate",
            "sleep" to "Sleep",
            "cholesterol" to "Cholesterol",
            "triglycerides" to "Triglycerides",
            "medications" to "Medications",
            "symptoms" to "Symptoms",
            "lab_results" to "Lab Results",
            "smoking" to "Smoking",
            "water_intake" to "Water Intake",
            "exercise" to "Exercise",
            "attachments" to "Attachments",
            "emergency_info" to "Emergency Info",
            "health_summary" to "Health Summary",
            "search" to "Search",
            "ai_health_assistant" to "AI Health Assistant",
            
            // Subtitles/Status
            "elevated" to "ELEVATED",
            "normal" to "NORMAL",
            "high" to "HIGH",
            "low" to "LOW",
            "dosage" to "Dosage",
            "frequency" to "Frequency",
            "notes" to "Notes",
            "timestamp" to "Date/Time",
            "active" to "Active",
            "inactive" to "Inactive",
            "severity" to "Severity",
            "reference_range" to "Reference Range",
            "allergies" to "Allergies",
            "chronic_conditions" to "Chronic Conditions",
            "blood_type" to "Blood Type",
            "full_name" to "Full Name",
            "emergency_contact" to "Emergency Contact Name",
            "emergency_phone" to "Emergency Contact Phone",
            "additional_notes" to "Additional Medical Notes",

            // Actions & Settings
            "theme" to "Theme",
            "system" to "SYSTEM",
            "light" to "LIGHT",
            "dark" to "DARK",
            "language" to "Language",
            "height_bmi" to "Height (cm) for BMI",
            "save_height" to "Save height",
            "ai_provider" to "AI Provider",
            "model_name" to "Model name",
            "add_record" to "Add Record",
            "add" to "Add",
            "save" to "Save",
            "delete" to "Delete",
            "cancel" to "Cancel",
            "quick_water" to "+250ml water",
            "export_data" to "Export Data (TXT / CSV / JSON / PDF)",
            "backup_data" to "Backup (ZIP)",
            "no_records" to "No records found.",
            "api_key" to "LLM API Key (Stored securely)",
            "save_api_key" to "Save Settings & Keys",
            "enter_value" to "Enter value",
            
            // History Headers
            "history" to "History & Trends",
            "systolic" to "Systolic",
            "diastolic" to "Diastolic",
            "value" to "Value",
            "unit" to "Unit",
            "hours" to "Hours",
            "select_image" to "Attach Health Image",
            "mood" to "Mood",
            "mood_score" to "How are you feeling?",
            "family_members" to "Family Members",
            "weekly_summary" to "Weekly AI Summary",
            "water_goal" to "Daily Water Goal",
            "dose_log" to "Dose Log",
            "mark_taken" to "Mark Taken",
            "mark_skipped" to "Mark Skipped",
            "relationship" to "Relationship",
            "date_of_birth" to "Date of Birth",

            // Multi-profile, height tracking, relationships, ZIP
            "me" to "Me",
            "tracking_for" to "Tracking for",
            "height_track" to "Height / Length",
            "add_height" to "Add Height",
            "edit_height" to "Edit Height",
            "rel_wife" to "Wife",
            "rel_husband" to "Husband",
            "rel_son" to "Son",
            "rel_daughter" to "Daughter",
            "rel_father" to "Father",
            "rel_mother" to "Mother",
            "rel_brother" to "Brother",
            "rel_sister" to "Sister",
            "rel_other" to "Other",
            "export_zip_full" to "Export Full ZIP (with files)",
            "import_zip" to "Import ZIP Backup",
            // Period tracking
            "period_track" to "Period Tracker",
            "add_period" to "Log Period",
            "edit_period" to "Edit Period",
            "period_start" to "Start Date",
            "period_end" to "End Date",
            "period_ongoing" to "Ongoing",
            "flow_level" to "Flow",
            "flow_light" to "Light",
            "flow_medium" to "Medium",
            "flow_heavy" to "Heavy",
            "avg_cycle" to "Average Cycle",
            "next_expected" to "Next Expected",
            "days_unit" to "days",
            "duration_label" to "Duration",
            // Onboarding
            "choose_language" to "Choose your language",
            "restore_from_backup" to "I have a backup — Restore from JSON",
            "import_failed" to "Import failed",
            "onboarding_welcome" to "Welcome to My Medical Journal",
            "onboarding_subtitle" to "Your personal health companion",
            "get_started" to "Get Started",
            "personal_info" to "Personal Information",
            "medical_info" to "Medical Information",
            "sex" to "Sex",
            "male" to "Male",
            "female" to "Female",
            "height_cm" to "Height (cm)",
            "weight_kg" to "Weight (kg)",
            "blood_type_select" to "Blood Type",
            "next_step" to "Next",
            "previous" to "Back",
            "finish_setup" to "Finish Setup",
            "step_of" to "Step %1 of %2",
            "conditions_hint" to "e.g. Diabetes, Hypertension",
            "allergies_hint" to "e.g. Penicillin, Sulfa",
            "unit_mgdl" to "mg/dL",
            "unit_mmol" to "mmol/L",
            "skip" to "Skip",

            // Backup & Export for Doctor
            "export_for_doctor" to "Export for Doctor",
            "doctor_export_desc" to "Share a CSV of your Blood Pressure, Blood Sugar, Weight, Sleep, Symptom and Lab Result records with your doctor (e.g. for import into DataDoctorPro).",
            "last_sent" to "Last sent",
            "never" to "Never",
            "days_30" to "30 Days",
            "days_90" to "90 Days",
            "all_time" to "All Time",
            "send_new_records" to "Send New Records Since Last Export",
            "backup_sync" to "Backup & Restore",
            "backup_desc" to "Backup and restore your medical journal records on this device.",
            "local_backup" to "Local Device Backup",
            "last_backup" to "Last backup",
            "back_up" to "Back Up",
            "restore" to "Restore",
            "export_media_zip" to "Export Media ZIP",

            // i18n completions — dialog titles
            "update" to "Update",
            "record_bp" to "Record Blood Pressure",
            "edit_bp" to "Edit Blood Pressure",
            "add_weight" to "Add Weight Record",
            "edit_weight" to "Edit Weight",
            "add_medication" to "Add Medication",
            "edit_medication" to "Edit Medication",
            "record_symptom" to "Record Symptom",
            "edit_symptom" to "Edit Symptom",
            "log_sleep" to "Log Sleep",
            "edit_sleep" to "Edit Sleep",
            "add_lab_result" to "Add Lab Result",
            "edit_lab_result" to "Edit Lab Result",
            "enter_attachment" to "Enter Attachment Details",
            "restore_status" to "Restore Status",

            // Form field labels
            "systolic_mmhg" to "Systolic (mmHg)",
            "diastolic_mmhg" to "Diastolic (mmHg)",
            "heart_rate_bpm" to "Heart Rate (bpm)",
            "blood_sugar_value" to "Blood Sugar Value",
            "weight_kg_label" to "Weight (kg)",
            "medication_name" to "Medication Name",
            "dosage_hint" to "Dosage (e.g. 10mg / 500mg)",
            "frequency_hint" to "Frequency (e.g. Once daily / evening)",
            "symptom_desc" to "Symptom Description",
            "hours_slept" to "Hours slept",
            "test_name_hint" to "Test Name (e.g. Cholesterol)",
            "measurement_value" to "Measurement Value",
            "unit_hint" to "Unit (e.g. mg/dL, mmol/L)",
            "ref_range_hint" to "Reference Range (e.g. 70-100, < 200)",
            "log_amount" to "Log amount",
            "attachment_title" to "Title / Description",
            "unit_short" to "Unit",
            "measurement_category" to "Measurement Type / Category",
            "severity_status" to "Severity Status",

            // Status & messages
            "no_attachments" to "No attachments loaded.",
            "restore_successful" to "Restore successful! All records imported.",
            "backup_saved" to "Backup saved successfully!",
            "search_hint_text" to "Type any term above to search instantly.",

            // AI/Summary labels
            "mood_log" to "Mood Log",
            "ai_chat" to "Chat",
            "generating_summary" to "Generating your 7-day health summary...",
            "ai_health_report" to "AI Weekly Health Report",
            "ask_assistant" to "Ask your health assistant...",
            "generate_summary" to "Generate Weekly Summary",
            "log_mood_btn" to "Log Mood",
            "send_btn" to "Send",

            // Search labels
            "bp_comments" to "Blood Pressure Comments",
            "weight_comments" to "Weight Entry Comments",
            "medication_matches" to "Medication Matches",
            "symptom_logs_label" to "Symptom Logs",

            // Appointments
            "appointments" to "Appointments",
            "add_appointment" to "Add Appointment",
            "edit_appointment" to "Edit Appointment",
            "appointment_title_field" to "Title (e.g. Cardiologist, Dr. Ahmad)",
            "appointment_type" to "Type",
            "appt_doctor" to "Doctor Visit",
            "appt_medication" to "Medication Reminder",
            "appt_lab" to "Lab Test",
            "appt_other" to "Other",
            "upcoming_appts" to "Upcoming",
            "past_appts" to "Past",
            "mark_complete" to "Mark Complete",
            "no_appointments" to "No appointments scheduled.",
            "completed_label" to "Completed",

            // Per-profile export
            "export_profile" to "Export Profile Data",
            "select_profile" to "Select Profile",
            "my_profile" to "My Profile",
            "share_whatsapp" to "Share via WhatsApp",
            "share_file" to "Share File",
            "export_child_data" to "Export Child / Family Member Data"
        ),
        "ar" to mapOf(
            "dashboard" to "لوحة البيانات",
            "home" to "الرئيسية",
            "track" to "المتابعة",
            "lifestyle" to "نمط الحياة",
            "more" to "المزيد",
            "settings" to "الإعدادات",
            
            // Medical parameters
            "blood_pressure" to "ضغط الدم",
            "blood_sugar" to "سكر الدم",
            "weight" to "الوزن",
            "heart_rate" to "نبض القلب",
            "sleep" to "النوم",
            "cholesterol" to "الكوليسترول",
            "triglycerides" to "الدهون الثلاثية",
            "medications" to "الأدوية",
            "symptoms" to "الأعراض",
            "lab_results" to "نتائج المختبر",
            "smoking" to "التدخين",
            "water_intake" to "شرب الماء",
            "exercise" to "التمارين الرياضية",
            "attachments" to "المرفقات",
            "emergency_info" to "معلومات الطوارئ",
            "health_summary" to "ملخص صحي",
            "search" to "البحث",
            "ai_health_assistant" to "مساعد الصحة الذكي",
            
            // Subtitles/Status
            "elevated" to "مرتفع نسبيًا",
            "normal" to "طبيعي",
            "high" to "مرتفع",
            "low" to "منخفض",
            "dosage" to "الجرعة",
            "frequency" to "التكرار",
            "notes" to "ملاحظات",
            "timestamp" to "التاريخ والوقت",
            "active" to "نشط",
            "inactive" to "غير نشط",
            "severity" to "الشدة",
            "reference_range" to "النطاق المرجعي",
            "allergies" to "الحساسية",
            "chronic_conditions" to "الأمراض المزمنة",
            "blood_type" to "فصيلة الدم",
            "full_name" to "الاسم الكامل",
            "emergency_contact" to "اسم جهة اتصال الطوارئ",
            "emergency_phone" to "هاتف جهة اتصال الطوارئ",
            "additional_notes" to "ملاحظات طبية إضافية",

            // Actions & Settings
            "theme" to "المظهر",
            "system" to "النظام",
            "light" to "فاتح",
            "dark" to "داكن",
            "language" to "اللغة",
            "height_bmi" to "الطول (سم) لحساب كتلة الجسم",
            "save_height" to "حفظ الطول",
            "ai_provider" to "مزود الذكاء الاصطناعي",
            "model_name" to "اسم النموذج",
            "add_record" to "إضافة سجل",
            "add" to "إضافة",
            "save" to "حفظ",
            "delete" to "حذف",
            "cancel" to "إلغاء",
            "quick_water" to "+250مل ماء",
            "export_data" to "تصدير البيانات (TXT / CSV / JSON / PDF)",
            "backup_data" to "نسخ احتياطي (ZIP)",
            "no_records" to "لا توجد سجلات بعد.",
            "api_key" to "مفتاح API الخاص بالذكاء الاصطناعي",
            "save_api_key" to "حفظ الإعدادات والمفاتيح",
            "enter_value" to "أدخل القيمة",
            
            // History Headers
            "history" to "السجل والمؤشرات",
            "systolic" to "الانقباضي",
            "diastolic" to "الانبساطي",
            "value" to "القيمة",
            "unit" to "الوحدة",
            "hours" to "ساعات",
            "select_image" to "إرفاق صورة طبية",
            "mood" to "الحالة المزاجية",
            "mood_score" to "كيف تشعر الآن؟",
            "family_members" to "أفراد الأسرة",
            "weekly_summary" to "ملخص أسبوعي بالذكاء الاصطناعي",
            "water_goal" to "هدف الماء اليومي",
            "dose_log" to "سجل الجرعات",
            "mark_taken" to "تم أخذها",
            "mark_skipped" to "تم التخطي",
            "relationship" to "العلاقة",
            "date_of_birth" to "تاريخ الميلاد",

            // Multi-profile, height tracking, relationships, ZIP
            "me" to "أنا",
            "tracking_for" to "التتبع لـ",
            "height_track" to "الطول",
            "add_height" to "إضافة طول",
            "edit_height" to "تعديل الطول",
            "rel_wife" to "زوجة",
            "rel_husband" to "زوج",
            "rel_son" to "ابن",
            "rel_daughter" to "ابنة",
            "rel_father" to "أب",
            "rel_mother" to "أم",
            "rel_brother" to "أخ",
            "rel_sister" to "أخت",
            "rel_other" to "أخرى",
            "export_zip_full" to "تصدير ملف ZIP كامل (مع الملفات)",
            "import_zip" to "استيراد نسخة ZIP",
            // Period tracking
            "period_track" to "متتبع الدورة الشهرية",
            "add_period" to "تسجيل دورة",
            "edit_period" to "تعديل الدورة",
            "period_start" to "تاريخ البداية",
            "period_end" to "تاريخ النهاية",
            "period_ongoing" to "مستمرة",
            "flow_level" to "الغزارة",
            "flow_light" to "خفيفة",
            "flow_medium" to "متوسطة",
            "flow_heavy" to "غزيرة",
            "avg_cycle" to "متوسط الدورة",
            "next_expected" to "الموعد المتوقع القادم",
            "days_unit" to "يوم",
            "duration_label" to "المدة",
            // Onboarding
            "choose_language" to "اختر لغتك",
            "restore_from_backup" to "لدي نسخة احتياطية — استعادة من JSON",
            "import_failed" to "فشل الاستيراد",
            "onboarding_welcome" to "مرحباً في مجلة صحتي",
            "onboarding_subtitle" to "رفيقك الصحي الشخصي",
            "get_started" to "ابدأ الآن",
            "personal_info" to "المعلومات الشخصية",
            "medical_info" to "المعلومات الطبية",
            "sex" to "الجنس",
            "male" to "ذكر",
            "female" to "أنثى",
            "height_cm" to "الطول (سم)",
            "weight_kg" to "الوزن (كغ)",
            "blood_type_select" to "فصيلة الدم",
            "next_step" to "التالي",
            "previous" to "السابق",
            "finish_setup" to "إتمام الإعداد",
            "step_of" to "الخطوة %1 من %2",
            "conditions_hint" to "مثال: السكري، ضغط الدم",
            "allergies_hint" to "مثال: البنسلين، السلفا",
            "unit_mgdl" to "mg/dL",
            "unit_mmol" to "mmol/L",
            "skip" to "تخطي",

            // Backup & Export for Doctor
            "export_for_doctor" to "التصدير للطبيب",
            "doctor_export_desc" to "شارك ملف CSV يحتوي على سجلات ضغط الدم وسكر الدم والوزن والنوم والأعراض ونتائج المختبر مع طبيبك.",
            "last_sent" to "آخر إرسال",
            "never" to "لا يوجد",
            "days_30" to "٣٠ يوماً",
            "days_90" to "٩٠ يوماً",
            "all_time" to "كل الوقت",
            "send_new_records" to "إرسال السجلات الجديدة منذ آخر تصدير",
            "backup_sync" to "النسخ الاحتياطي والاسترداد",
            "backup_desc" to "احتفظ بنسخة احتياطية من سجلاتك الصحية أو استردّها على هذا الجهاز.",
            "local_backup" to "النسخ الاحتياطي المحلي",
            "last_backup" to "آخر نسخة احتياطية",
            "back_up" to "نسخ احتياطي",
            "restore" to "استرداد",
            "export_media_zip" to "تصدير ملفات الوسائط (ZIP)",

            // i18n completions — dialog titles
            "update" to "تحديث",
            "record_bp" to "تسجيل ضغط الدم",
            "edit_bp" to "تعديل ضغط الدم",
            "add_weight" to "إضافة سجل وزن",
            "edit_weight" to "تعديل الوزن",
            "add_medication" to "إضافة دواء",
            "edit_medication" to "تعديل الدواء",
            "record_symptom" to "تسجيل عَرَض",
            "edit_symptom" to "تعديل العَرَض",
            "log_sleep" to "تسجيل النوم",
            "edit_sleep" to "تعديل سجل النوم",
            "add_lab_result" to "إضافة نتيجة مختبر",
            "edit_lab_result" to "تعديل نتيجة المختبر",
            "enter_attachment" to "أدخل تفاصيل المرفق",
            "restore_status" to "حالة الاسترداد",

            // Form field labels
            "systolic_mmhg" to "الانقباضي (ملم زئبق)",
            "diastolic_mmhg" to "الانبساطي (ملم زئبق)",
            "heart_rate_bpm" to "معدل القلب (نبضة/دقيقة)",
            "blood_sugar_value" to "قيمة سكر الدم",
            "weight_kg_label" to "الوزن (كغ)",
            "medication_name" to "اسم الدواء",
            "dosage_hint" to "الجرعة (مثال: 10mg / 500mg)",
            "frequency_hint" to "التكرار (مثال: مرة يومياً / مساءً)",
            "symptom_desc" to "وصف العَرَض",
            "hours_slept" to "ساعات النوم",
            "test_name_hint" to "اسم الاختبار (مثال: الكوليسترول)",
            "measurement_value" to "قيمة القياس",
            "unit_hint" to "الوحدة (مثال: mg/dL)",
            "ref_range_hint" to "النطاق المرجعي (مثال: 70-100، أو < 200)",
            "log_amount" to "سجّل الكمية",
            "attachment_title" to "العنوان / الوصف",
            "unit_short" to "الوحدة",
            "measurement_category" to "نوع القياس / الفئة",
            "severity_status" to "مستوى الشدة",

            // Status & messages
            "no_attachments" to "لا توجد مرفقات بعد.",
            "restore_successful" to "تم الاسترداد بنجاح! تم استيراد جميع السجلات.",
            "backup_saved" to "تم حفظ النسخة الاحتياطية بنجاح!",
            "search_hint_text" to "اكتب أي كلمة للبحث الفوري.",

            // AI/Summary labels
            "mood_log" to "سجل المزاج",
            "ai_chat" to "المحادثة",
            "generating_summary" to "جارٍ إنشاء ملخصك الصحي لـ 7 أيام...",
            "ai_health_report" to "التقرير الصحي الأسبوعي بالذكاء الاصطناعي",
            "ask_assistant" to "اسأل مساعدك الصحي...",
            "generate_summary" to "إنشاء الملخص الأسبوعي",
            "log_mood_btn" to "سجّل المزاج",
            "send_btn" to "إرسال",

            // Search labels
            "bp_comments" to "تعليقات ضغط الدم",
            "weight_comments" to "تعليقات سجلات الوزن",
            "medication_matches" to "نتائج الأدوية",
            "symptom_logs_label" to "سجلات الأعراض",

            // Appointments
            "appointments" to "المواعيد",
            "add_appointment" to "إضافة موعد",
            "edit_appointment" to "تعديل الموعد",
            "appointment_title_field" to "العنوان (مثال: طبيب القلب، د. أحمد)",
            "appointment_type" to "النوع",
            "appt_doctor" to "زيارة طبيب",
            "appt_medication" to "تذكير دواء",
            "appt_lab" to "فحص مختبر",
            "appt_other" to "أخرى",
            "upcoming_appts" to "القادمة",
            "past_appts" to "السابقة",
            "mark_complete" to "تم",
            "no_appointments" to "لا توجد مواعيد مجدولة.",
            "completed_label" to "مكتمل",

            // Per-profile export
            "export_profile" to "تصدير بيانات الملف الشخصي",
            "select_profile" to "اختر الملف الشخصي",
            "my_profile" to "ملفي الشخصي",
            "share_whatsapp" to "مشاركة عبر واتساب",
            "share_file" to "مشاركة الملف",
            "export_child_data" to "تصدير بيانات الطفل / أحد أفراد الأسرة"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
